// ============================================================================
// DinoRunner Audio Test Tool
// ============================================================================
// Standalone executable that verifies all procedural sound effects and
// background music generated by AudioManager.
//
// Compile (from dino_game/):
//   g++ -std=c++17 -I include -I sfml/include tools/test_audio.cpp \
//       src/core/AudioManager.cpp src/abi_compat.cpp \
//       -L sfml/lib -lsfml-graphics-s -lsfml-window-s -lsfml-system-s \
//       -lfreetype -lstdc++ -lws2_32 -lwinmm -lopengl32 -lgdi32 \
//       -lole32 -loleaut32 -luuid -o tools/test_audio.exe
//
// Run:
//   ./tools/test_audio.exe
// ============================================================================

#include "core/AudioManager.h"
#include <iostream>
#include <thread>
#include <chrono>

#ifdef _WIN32
#include <windows.h>
#include <conio.h>
#else
#include <unistd.h>
#include <termios.h>
#include <fcntl.h>
#endif

// Simple cross-platform sleep
void sleepMs(int ms) {
    std::this_thread::sleep_for(std::chrono::milliseconds(ms));
}

#ifndef _WIN32
int kbhit(void) {
    struct termios oldt, newt;
    int ch;
    int oldf;
    tcgetattr(STDIN_FILENO, &oldt);
    newt = oldt;
    newt.c_lflag &= ~(ICANON | ECHO);
    tcsetattr(STDIN_FILENO, TCSANOW, &newt);
    oldf = fcntl(STDIN_FILENO, F_GETFL, 0);
    fcntl(STDIN_FILENO, F_SETFL, oldf | O_NONBLOCK);
    ch = getchar();
    tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
    fcntl(STDIN_FILENO, F_SETFL, oldf);
    if (ch != EOF) {
        ungetc(ch, stdin);
        return 1;
    }
    return 0;
}

int getch(void) {
    struct termios oldt, newt;
    int ch;
    tcgetattr(STDIN_FILENO, &oldt);
    newt = oldt;
    newt.c_lflag &= ~(ICANON | ECHO);
    tcsetattr(STDIN_FILENO, TCSANOW, &newt);
    ch = getchar();
    tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
    return ch;
}
#endif

void printHeader(const char* title) {
    std::cout << "\n";
    std::cout << "===============================================\n";
    std::cout << "  " << title << "\n";
    std::cout << "===============================================\n";
}

void printPrompt() {
    std::cout << "\n  >> Press SPACE to continue, Q to quit << \n";
}

bool waitForUser() {
    while (true) {
#ifdef _WIN32
        if (_kbhit()) {
            int ch = _getch();
            if (ch == 'q' || ch == 'Q' || ch == 27) return false; // ESC
            if (ch == ' ') return true;
        }
#else
        if (kbhit()) {
            int ch = getch();
            if (ch == 'q' || ch == 'Q' || ch == 27) return false;
            if (ch == ' ') return true;
        }
#endif
        sleepMs(50);
    }
}

int main() {
    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════════╗\n";
    std::cout << "║     DinoRunner - Audio Test Tool            ║\n";
    std::cout << "║──────────────────────────────────────────────║\n";
    std::cout << "║  This tool plays all procedural sounds      ║\n";
    std::cout << "║  generated by AudioManager.                 ║\n";
    std::cout << "║                                              ║\n";
    std::cout << "║  Controls: SPACE = next sound               ║\n";
    std::cout << "║            Q/ESC = quit                     ║\n";
    std::cout << "╚══════════════════════════════════════════════╝\n";

    // Initialize AudioManager and generate all sounds
    printHeader("Initializing AudioManager...");
    AudioManager audio;
    audio.init();
    std::cout << "  AudioManager initialized successfully!\n";
    sleepMs(500);
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 1: MENU SELECT (short beep)
    // ===================================================================
    printHeader("Test 1: Menu Select Sound");
    std::cout << "  A short, crisp beep (1000Hz, 60ms).\n";
    std::cout << "  Should sound like a UI selection click.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("select");
        sleepMs(300);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 2: JUMP (rising sweep)
    // ===================================================================
    printHeader("Test 2: Jump Sound");
    std::cout << "  A quick rising sine sweep (200→700Hz, 180ms).\n";
    std::cout << "  Should sound like a 'boing' or spring.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("jump");
        sleepMs(400);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 3: LAND (soft thud)
    // ===================================================================
    printHeader("Test 3: Landing Sound");
    std::cout << "  A soft low-frequency thud (60→30Hz, 100ms).\n";
    std::cout << "  Should sound like feet hitting the ground.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("land");
        sleepMs(300);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 4: DASH (whoosh)
    // ===================================================================
    printHeader("Test 4: Dash Sound");
    std::cout << "  A rising-frequency whoosh with noise (150→900Hz, 300ms).\n";
    std::cout << "  Should sound like a quick speed burst.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("dash");
        sleepMs(500);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 5: COIN (two-tone chime)
    // ===================================================================
    printHeader("Test 5: Coin Sound");
    std::cout << "  A bright two-tone chime (A5→E6, ~200ms).\n";
    std::cout << "  Classic 'ding-ding' coin collect sound.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("coin");
        sleepMs(500);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 6: DAMAGE (low thud)
    // ===================================================================
    printHeader("Test 6: Damage Sound");
    std::cout << "  A low-frequency thud with noise (100→40Hz, 250ms).\n";
    std::cout << "  Should sound like being hit or hurt.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("damage");
        sleepMs(500);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 7: SHIELD (shimmer)
    // ===================================================================
    printHeader("Test 7: Shield Sound");
    std::cout << "  A high-frequency shimmer with noise (2000→4000Hz, 200ms).\n";
    std::cout << "  Should sound like a protective barrier absorbing impact.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("shield");
        sleepMs(400);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 8: POWER-UP (ascending arpeggio)
    // ===================================================================
    printHeader("Test 8: Power-Up Sound");
    std::cout << "  An ascending arpeggio (C5→E5→G5→C6, ~400ms).\n";
    std::cout << "  Classic 'power-up collected' jingle.\n\n";
    for (int i = 0; i < 3; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/3)\r";
        std::cout.flush();
        audio.playSound("powerup");
        sleepMs(700);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 9: GAME OVER (descending tone)
    // ===================================================================
    printHeader("Test 9: Game Over Sound");
    std::cout << "  A slow descending tone (400→80Hz, 800ms).\n";
    std::cout << "  Should sound sad/dramatic.\n\n";
    for (int i = 0; i < 2; i++) {
        std::cout << "  ▶ Playing... (" << (i+1) << "/2)\r";
        std::cout.flush();
        audio.playSound("gameover");
        sleepMs(1200);
    }
    std::cout << "\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 10: BACKGROUND MUSIC
    // ===================================================================
    printHeader("Test 10: Background Music");
    std::cout << "  Procedural background music loop (16 seconds, 140 BPM).\n";
    std::cout << "  Melody (pentatonic) + bass + chords + percussion.\n\n";
    std::cout << "  Starting music...\n";
    audio.startMusic();
    std::cout << "  ▶ Music playing for 8 seconds...\n";
    sleepMs(8000);

    std::cout << "  ▶ Setting music volume to 30%...\n";
    audio.setMusicVolume(30.0f);
    sleepMs(3000);

    std::cout << "  ▶ Setting music volume to 80%...\n";
    audio.setMusicVolume(80.0f);
    sleepMs(3000);

    std::cout << "  ▶ Muting audio...\n";
    audio.setMuted(true);
    sleepMs(2000);
    std::cout << "  (Should be silent for 2 seconds)\n";

    std::cout << "  ▶ Unmuting audio...\n";
    audio.setMuted(false);
    sleepMs(3000);

    std::cout << "  Stopping music.\n";
    audio.stopMusic();
    sleepMs(500);
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Test 11: RAPID-FIRE SOUNDS (stress test)
    // ===================================================================
    printHeader("Test 11: Rapid-Fire Stress Test");
    std::cout << "  Playing multiple sounds simultaneously to test\n";
    std::cout << "  concurrent playback and cleanup.\n\n";

    std::cout << "  ▶ Firing 10 coin + 5 damage + 3 jump sounds rapidly...\n";
    for (int i = 0; i < 10; i++) {
        audio.playSound("coin");
        audio.playSound("damage");
        audio.playSound("jump");
        sleepMs(50);
    }
    sleepMs(2000);
    std::cout << "  ▶ All sounds should have played without crashing.\n";
    printPrompt();
    if (!waitForUser()) return 0;

    // ===================================================================
    // Done
    // ===================================================================
    printHeader("Audio Test Complete!");
    std::cout << "  All " << 11 << " tests completed.\n\n";
    std::cout << "  If you heard all sounds correctly, the audio system\n";
    std::cout << "  is working properly!\n";
    std::cout << "\n";
    std::cout << "  If some sounds were missing or distorted:\n";
    std::cout << "  - Check Windows volume mixer (audio may be muted)\n";
    std::cout << "  - Check that your speakers/headphones are connected\n";
    std::cout << "  - The waveOut API may have limitations on your system\n";
    std::cout << "\n";
    std::cout << "  Press Q or ESC to exit.\n";

    while (true) {
#ifdef _WIN32
        if (_kbhit()) {
            int ch = _getch();
            if (ch == 'q' || ch == 'Q' || ch == 27) break;
        }
#else
        if (kbhit()) {
            int ch = getch();
            if (ch == 'q' || ch == 'Q' || ch == 27) break;
        }
#endif
        sleepMs(50);
    }

    return 0;
}
